name: Firmware Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t firmware-builder .

      - name: Build Firmware
        run: |
          docker run --rm firmware-builder ./build.sh

      - name: Debug Files
        run: |
          pwd
          find . -type f | grep -E "\.(elf|bin|hex|map)$" || true